### ISSUE TITLE
Improve documentation on in-cluster connection

### ISSUE THREAD

**Issue by znorris** [coryodaniel/k8s#250]
I'm used to leveraging the in cluster configuration method found in [official](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#using-official-client-libraries) [libraries](https://github.com/kubernetes-client/python/blob/2f546b9dcbf92cbeb123d15e23bcc4e343ef0db6/kubernetes/base/config/incluster_config.py#L37).

I've looked around k8s but I haven't seen a module that implements this. I would find it useful to have this feature as it would provide a straight forward Google Kubernetes Engine auth integration ~while using [workload identity](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity)~.

**Comment by mruoss** [comment]
Hi @znorris 

Have you seen the [usage guide](https://github.com/coryodaniel/k8s/blob/develop/guides/connections.md) on connections?

Since you're writing "in cluster", I'm assuming you're using `k8s` inside a pod and are trying to access resources inside the same cluster this pod is running in. If that's the case, all you need is to have RBAC set up correctly for the pod's service account and call `K8s.Conn.from_service_account/1` to get a `%K8s.Conn{}` struct used to connect to the cluster.

Given RBAC is set up accordingly, the following code would get a list of namespaces of the cluster this code is running in:

```elixir
{:ok, conn} = K8s.Conn.from_service_account()

{:ok, namespace_list} = 
  K8s.Client.list("v1", "Namespace")
  |> K8s.Client.put_conn(conn)
  |> K8s.Client.run()
```

I'm a bit confused on why you've mentioned workload identity. Running inside GKE you would use workload identity to authenticate as a Google Service Account in order to access Google Cloud resources, e.g. Google Cloud Storage etc. But that's not what this library is used for.

Unless we're talking about the use case where your code is running in a GitHub workflow, trying to access the GKE cluster using federated workload identity. Is that it?

**Comment by znorris** [comment]
@mruoss Thanks for your quick reply. I'm doing too many things at once and erroneously conflated workload identity.

I did read all if it several times. However, it wasn't clear to me that this was the in cluster configuration as I've never used the service account directory before. Perhaps adding to the documentation will prevent others from making this mistake.

This func is exactly what I was looking for.

**Comment by mruoss** [comment]
> This func is exactly what I was looking for.

Ok, glad it's so easy then. :)

> Perhaps adding to the documentation will prevent others from making this mistake.

I'll gladly clarify the docs. This is a part that Cory implemented and documented and I've never gone over it. Once you're too deep you don't look at those "first step" docs anymore. 

Leaving this open for now.

**Comment by mruoss** [comment]
Decided to improve the `@moduledoc` and `@doc` of `K8s.Conn`. I think it's the first place people look (right @znorris?)

**Comment by znorris** [comment]
Thank you @mruoss, very helpful.
